### ISSUE TITLE
Distinct URL sub-tags not working

### ISSUE THREAD

**Issue by Narevau** [016/lm180_iEVE_Echoes#20]
I have tried out the sub-tags you mentioned a while ago. They seem to work fine for Ore,Miner and Planetary but:
https://ieve.yiilib.com/#/material/11  
https://ieve.yiilib.com/#/material/21
lead to the wrong things (to Miner and not to Debris/Datacore).

**Comment by 016** [comment]
@Narevau thx for your feedback, I fixed it, it's a bug on data level, everything should working now, plz test again when u have time.

**Comment by Narevau** [comment]
Sorry but the 2 URL´s are still not working for me :/ Same as before, still lead to the Miner tab

**Comment by 016** [comment]
![Screen Shot 2020-09-14 at 11 34 20 PM](https://user-images.githubusercontent.com/7589575/93106487-e8620080-f6e2-11ea-9977-ddda13fc0893.jpg)
![Screen Shot 2020-09-14 at 11 34 28 PM](https://user-images.githubusercontent.com/7589575/93106492-eac45a80-f6e2-11ea-8fb5-8f34f4fbdd50.jpg)
I just did a double check, it's working for me, try clean your browser cache.

**Comment by 016** [comment]
let me know if u still have problem
